# Generated by Django 4.2.3 on 2023-07-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_created_at', models.DateTimeField(auto_created=True)),
                ('cli_nombre', models.CharField(max_length=100)),
                ('cli_celular', models.CharField(max_length=20)),
                ('cli_correo', models.EmailField(max_length=254)),
                ('cli_direccion', models.CharField(max_length=200)),
                ('cli_ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_created_at', models.DateTimeField(auto_created=True)),
                ('pro_nombre', models.CharField(max_length=100)),
                ('pro_cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ped_created_at', models.DateTimeField(auto_created=True)),
                ('ped_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ped_fecha', models.DateField()),
                ('ped_estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('ped_pagado', models.BooleanField()),
                ('ped_regla_envio', models.CharField(choices=[('domicilio', 'Domicilio'), ('recoge', 'Recoge en punto')], max_length=20)),
                ('ped_observaciones', models.TextField()),
                ('ped_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.cliente')),
                ('ped_items', models.ManyToManyField(to='proyecto.producto')),
            ],
        ),
    ]
